sudo: false
language: cpp
compiler: gcc
python:
  - "3.4"
branches:
  only:
    - master
    - develop
    - /^release\/.*/
    - /^hotfix\/.*/

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libopencv-dev
      - libeigen3-dev
      - libflann-dev
      - lcov

before_install:
  - pip install --user cpp-coveralls
  - pip install --user -v pyhamcrest
  - pip install --user nose
before_script:
  - git clone https://github.com/PointCloudLibrary/pcl.git /tmp/pcl
  - export PCL_DIR=/tmp/pcl
  - cd /tmp/pcl && cmake -DCMAKE_INSTALL_PREFIX=/tmp/libpcl .
  - make pcl_common/fast pcl_octree/fast pcl_io -j2
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - mkdir -p ~/src/DCL && mv ~/build/qiubix/DCL_BayesNetwork ~/src/DCL && mv ~/src/DCL/DCL_BayesNetwork ~/src/DCL/BayesNetwork
  - cd ~/src/DCL/BayesNetwork
  - ./install_discode.sh
script: cmake  -DCMAKE_BUILD_TYPE=Debug -DCOMPONENT_SIFTAdder=OFF -DCOMPONENT_SIFTFeatureMatcher=OFF -DCOMPONENT_SOMJSONReader=OFF -DCOMPONENT_MapMultiplicity=OFF . && make && make test
after_success:
  - make test ARGS="-V"
  - coveralls --exclude lib --exclude tests --exclude ext --gcov-options '\-lp'
  - cd ~/src && git clone https://github.com/qiubix/DisCODeRunner.git && cd DisCODeRunner && git checkout origin/develop
  - python setup.py install --user
  - cd ~/src/DCL/BayesNetwork && make install
  - export LD_LIBRARY_PATH=/home/travis/src/DCL/BayesNetwork/dist/lib:$LD_LIBRARY_PATH
  - nosetests -v --nocapture test/acceptance
