language: cpp
compiler:
  - gcc
  - cmake

before_script:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev libopencv-dev libpcl-all
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - ./install_discode.sh
# Change this to your needs
script: cmake . && make
