sudo: true
language: cpp
compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest/ppa
    - v-launchpad-jochen-sprickerhof-de/pcl
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.54-dev
    - libopencv-dev
    - libpcl-all
branches:
  only:
    - master
    - develop
    - /^release\/.*/
    - /^hotfix\/.*/
    - feature/optimizeDependencies
    - feature/C++11

before_script:
  - sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.8 libboost1.54-dev libopencv-dev libpcl-all
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  # tar xzf cmake-3.2.1.tar.gz
  # cd cmake-3.2.1 && cmake . && make -j3 && sudo make install
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - cd ~/build/qiubix/DCL_BayesNetwork
  - ./install_discode.sh
# Change this to your needs
script: cmake . && make && make test
