sudo: false
language: cpp
compiler: gcc
python:
  - "3.4"
branches:
  only:
    - master
    - develop
    - /^release\/.*/
    - /^hotfix\/.*/
    - feature/optimizeDependencies

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libopencv-dev
      - libeigen3-dev
      - libflann-dev
      - lcov

before_install:
  - pip install --user cpp-coveralls
  - pip install --user -v pyhamcrest
  - pip install --user nose
before_script:
  - git clone https://github.com/PointCloudLibrary/pcl.git /tmp/pcl
  - export PCL_DIR=/tmp/pcl
  - cd /tmp/pcl && cmake -DCMAKE_INSTALL_PREFIX=/tmp/libpcl .
    #       -DPCL_ONLY_CORE_POINT_TYPES=ON \
    #       -DBUILD_2d=OFF \
    #       -DBUILD_features=OFF \
    #       -DBUILD_filters=OFF \
    #       -DBUILD_geometry=OFF \
    #       -DBUILD_global_tests=OFF \
    #       -DBUILD_io=ON \
    #       -DBUILD_kdtree=OFF \
    #       -DBUILD_keypoints=OFF \
    #       -DBUILD_ml=OFF \
    #       -DBUILD_octree=ON \
    #       -DBUILD_outofcore=OFF \
    #       -DBUILD_people=OFF \
    #       -DBUILD_recognition=OFF \
    #       -DBUILD_registration=OFF \
    #       -DBUILD_sample_consensus=OFF \
    #       -DBUILD_search=OFF \
    #       -DBUILD_segmentation=OFF \
    #       -DBUILD_stereo=OFF \
    #       -DBUILD_surface=OFF \
    #       -DBUILD_tools=OFF \
    #       -DBUILD_tracking=OFF \
    #       -DBUILD_visualization=OFF .
  - make pcl_common/fast pcl_octree/fast pcl_io -j2
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - cd ~/build/qiubix/DCL_BayesNetwork
  - ./install_discode.sh
script: cmake  -DCMAKE_BUILD_TYPE=Debug -DCOMPONENT_SIFTAdder=OFF -DCOMPONENT_SIFTFeatureMatcher=OFF -DCOMPONENT_SOMJSONReader=OFF -DCOMPONENT_MapMultiplicity=OFF . && make && make test
after_success:
  - coveralls --exclude lib --exclude tests --exclude ext --gcov-options '\-lp'
  - cd ~/src && git clone https://github.com/qiubix/DisCODeRunner.git && cd DisCODeRunner
  - python setup.py install --user
  - cd ~/build/qiubix/DCL_BayesNetwork
  - mkdir -p data/test_tasks
  - nosetests -v test/acceptance
