sudo: false
language: cpp
compiler: gcc
branches:
  only:
    - master
    - develop
    - /^release\/.*/
    - /^hotfix\/.*/
    - feature/optimizeDependencies

addons:
  apt:
    sources:
      - boost-latest
    #      - v-launchpad-jochen-sprickerhof-de/pcl
    packages:
      - libboost1.55-all-dev
      - libopencv-dev
      - libeigen3-dev
      - libflann-dev
      - libvtk5-dev

before_script:
  # sudo add-apt-repository ppa:v-launchpad-jochen-sprickerhof-de/pcl -y
  # sudo apt-get update -qq
  # sudo apt-get install libboost-all-dev libopencv-dev libpcl-all
  # wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
  # tar xzf cmake-3.2.1.tar.gz
  # cd cmake-3.2.1 && cmake . && make -j3 && sudo make install
  - git clone https://github.com/PointCloudLibrary/pcl.git /tmp/pcl
  - mkdir /tmp/libpcl && cd /tmp/pcl && cmake -DCMAKE_INSTALL_PREFIX=/tmp/libpcl . && make pcl_common/fast pcl_octree/fast -j4
  - export PCL_DIR=/tmp/pcl/cmake
  - ln -s /tmp/pcl/build/lib /tmp/libpcl
  - export PATH=$PATH:/tmp/libpcl
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - cd ~/build/qiubix/DCL_BayesNetwork
  - ./install_discode.sh
# Change this to your needs
script: cmake . && make && make test
